language: node_js
node_js:
  - "12.12"

services:
  - docker

jobs:
  include:
    - stage: test frontend
      skip_cleanup: true
      script: cd frontend
      script: npm install
      script: npm run test
    - stage: test backend
      skip_cleanup: true
      script: cd backend
      script: npm install
      script: npm run test

deploy:
  provider: script
  skip_cleanup: true
  script: docker build -t xdronedsl/webapp:latest .
  script: bash docker_push.sh
  on:
    branch: master



