language: node_js
node_js:
  - "12.12"

services:
  - docker

before_install:
  - docker build -t xdronedsl/webapp:latest .
  - cd frontend; npm install
  - cd ../backend; npm install


jobs:
  include:
    # - stage: test frontend
    #   skip_cleanup: true
    #   script: "cd frontend; npm run test"
    # - stage: test backend
    #   skip_cleanup: true
    #   script: "cd backend; npm run test"
    - stage: publish
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script: bash docker_push.sh
        on:
          branch: master



