language: node_js
node_js:
  - "12.12"

services:
  - docker

before_install:
  - cd frontend
  - npm install
  - cd ../backend
  - npm install
  - cd ..

jobs:
  include:
    - stage: test frontend
      skip_cleanup: true
      script: "cd frontend; npm run test"
    - stage: test backend
      skip_cleanup: true
      script: "cd backend; npm run test"


      
deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_deploy.sh
  on:
    branch: master



